"""initial

Revision ID: 60894b05fcbb
Revises: 
Create Date: 2026-05-14 07:08:00.369642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60894b05fcbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_value', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cookie_file', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PARTIAL', 'DONE', 'FAILED', 'CANCELLED', 'FATAL', 'UPDATED', 'NEW', name='taskstatus'), nullable=True),
    sa.Column('video_status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=True),
    sa.Column('subtitle_status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=True),
    sa.Column('transcript_status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=True),
    sa.Column('article_status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('subtitle_path', sa.String(length=500), nullable=True),
    sa.Column('transcript_path', sa.String(length=500), nullable=True),
    sa.Column('article_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('server_updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'resource_id')
    )
    op.create_index('idx_tasks_platform', 'tasks', ['platform'], unique=False)
    op.create_index('idx_tasks_platform_status', 'tasks', ['platform', 'status'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_platform_status', table_name='tasks')
    op.drop_index('idx_tasks_platform', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('accounts')
    op.drop_table('platforms')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
